arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated-messages.txt
synthetic-package: false
output-dir: lib/l10n/gen_l10n